#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="5.2/5.2.2/+download/Plone-5.2.2-UnifiedInstaller.tgz"
URL="https://launchpad.net/plone/$VERSION"

dl $URL /usr/local/src

