#!/bin/sh -ex

SRC=/usr/local/src
DEST=/usr/local/share/plone

ADMIN_PASS=turnkey

# unpack and install
tar -zxf $SRC/Plone-*.tgz -C $SRC
rm $SRC/Plone-*.tgz

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
$SRC/Plone-*/install.sh --target=$DEST --password=$ADMIN_PASS zeo
unset HTTP_PROXY

rm -rf $SRC/Plone-*

# make plone clients listen on localhost (we proxy through via apache)
CONF=$DEST/zeocluster/buildout.cfg
sed -i "s|^http-address.*|http-address = 127.0.0.1:8080|" $CONF
sed -i "s|^client2-address.*|client2-address = 127.0.0.1:8081|" $CONF
cd $DEST/zeocluster
bin/buildout

# replace default overview with custom welcome page
mv $SRC/plone-overview.pt $DEST/buildout-cache/eggs/Products.CMFPlone-*.egg/Products/CMFPlone/browser/templates/plone-overview.pt

# enable initscript
update-rc.d plone defaults

# apache configuration
a2dissite 000-default
a2ensite plone
a2enmod proxy
a2enmod proxy_http
a2enmod rewrite

